import { StyleSheet, Platform } from "react-native";
import colors from "../../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.BACKGROUND_COLOR,
  },
  topHeader: {
    backgroundColor: colors.LIGHT,
    borderBottomWidth: 1,
    borderBottomColor: colors.BORDER_COLOR,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  headerBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.DARK,
    marginBottom: 4,
  },
  headerRightSpace: {
    width: 40,
  },
  searchBox: {
    marginHorizontal: 12,
    marginTop: 14,
    backgroundColor: colors.LIGHT,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.BORDER_COLOR,
    paddingHorizontal: 12,
    height: 44,
    flexDirection: "row",
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    height: "100%",
    fontSize: 14,
    paddingVertical: 0,
    color: colors.DARK,
    marginLeft: 8,
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  clearSearchBtn: {
    padding: 4,
    marginLeft: 4,
  },
  sectionHeader: {
    marginTop: 18,
    marginBottom: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 1.2,
    color: colors.SECONDARY,
  },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.PRIMARY,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.PRIMARY,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  modalSheet: {
    backgroundColor: colors.LIGHT,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: Platform.OS === "ios" ? 40 : 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.BORDER_COLOR,
  },
  modalHeading: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.DARK,
  },
  modalBody: {
    paddingHorizontal: 24,
    paddingVertical: 24,
  },
  addBtn: {
    backgroundColor: colors.PRIMARY,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 54,
    borderRadius: 12,
    gap: 8,
    marginTop: 10,
  },
  addBtnText: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.DARK,
  },
  cancelBtn: {
    alignItems: "center",
    marginTop: 12,
  },
  cancelText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.SECONDARY,
  },
  listContent: {
    paddingHorizontal: 12,
    paddingBottom: 120,
  },
  card: {
    backgroundColor: colors.LIGHT,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.BORDER_COLOR,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardTextWrap: {
    flex: 1,
  },
  categoryName: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.DARK,
  },
  categoryMeta: {
    marginTop: 4,
    fontSize: 13,
    color: colors.SECONDARY,
    fontWeight: "500",
  },
  emptyWrap: {
    paddingTop: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: {
    marginTop: 16,
    fontSize: 18,
    color: colors.SECONDARY,
    fontWeight: "600",
  },
  emptySubText: {
    marginTop: 8,
    fontSize: 14,
    color: colors.SECONDARY,
    fontWeight: "500",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 80,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: colors.SECONDARY,
    fontWeight: "500",
  },
  primaryBtn: { 
    backgroundColor: colors.PRIMARY, 
    height: 54, 
    borderRadius: 12, 
    justifyContent: "center", 
    alignItems: "center", 
    marginTop: 10,
    flexDirection: "row",
    gap: 8,
  },
  btnText: { 
    color: colors.DARK, 
    fontSize: 16, 
    fontWeight: "bold" 
  },
  deleteBtn: { 
    backgroundColor: colors.DANGER_COLOR, 
    height: 54, 
    borderRadius: 12, 
    justifyContent: "center", 
    alignItems: "center", 
    marginTop: 10,
    flexDirection: "row",
    gap: 8,
  },
  deleteText: { 
    color: colors.LIGHT, 
    fontSize: 16, 
    fontWeight: "bold" 
  },
  cancelBtn: { 
    alignItems: "center", 
    marginTop: 16 
  },
  cancelText: { 
    fontSize: 14, 
    fontWeight: "600", 
    color: colors.SECONDARY 
  }
});